import numpy as np
from sklearn.cluster import DBSCAN
from sklearn.metrics.cluster import normalized_mutual_info_score 


# Before you do anything, make sure you have run the NormaliseData project, and run the sHDBSCAN project.

# Input your local path to the folder you want to read input from and write output to
normalized_data_raw, sDBSCAN_clusters, epsilon, minPts = input().split()

# Input the path to a normalized data csv file. Remember to run the NormaliseData Program beforehand.
normalized_data = np.genfromtxt(normalized_data_raw, delimiter=";", skip_header=1)

# Input the csv filename for the output generated by the sDBSCAN
sDBSCAN = np.genfromtxt(sDBSCAN_clusters,dtype=int)
# Perform sklearns DBSCAN
clustering = DBSCAN(eps=float(epsilon), min_samples=int(minPts), metric='cosine').fit(normalized_data)

# Perform nmi
nmi = normalized_mutual_info_score(sDBSCAN, clustering.labels_)

# Print results
cl = {}
print("DBSCAN clusters:")
for elem in clustering.labels_:
    if elem not in cl:
        cl[int(elem)] = 1
    else:
        cl[int(elem)] = cl[int(elem)] + 1
print(cl)
cl = {}
print("sDBSCAN clusters")
for elem in sDBSCAN:
    if elem not in cl:
        cl[int(elem)] = 1
    else:
        cl[int(elem)] = cl[int(elem)] + 1

print(cl)
print(f"nmi : {(100 * nmi):.2f}%")