import numpy as np
from sklearn.cluster import DBSCAN
from sklearn.metrics.cluster import normalized_mutual_info_score 
import os
import time


# Before you do anything, make sure you have run the NormaliseData project, and run the sHDBSCAN project.
# Input your local path to the folder you want to read input from and write output to
pathToOut, sDBSCAN_stats_path, normalized_data_raw, sDBSCAN_clusters, epsilon, minPts = input().split()

# Input the path to a normalized data csv file. Remember to run the NormaliseData Program beforehand.
normalized_data = np.genfromtxt(pathToOut+normalized_data_raw, delimiter=";", skip_header=1)

# Input the csv filename for the output generated by the sDBSCAN
sDBSCAN = np.genfromtxt(sDBSCAN_clusters,dtype=int)

#
previously_stored_DBSCAN_path = pathToOut+r"\previously_stored_dbscan"
if not os.path.exists(previously_stored_DBSCAN_path):
    with open(previously_stored_DBSCAN_path, "w") as file:
        file.write("Nothing")

f = open(previously_stored_DBSCAN_path)
previous_dbscan = f.read()
f.close()

if(str(previous_dbscan) != str(normalized_data.shape)): #Whether to compute the dbscan or use a saved one.
    # Perform SCIKIT DBSCAN
    start = time.perf_counter()

    clustering = DBSCAN(eps=float(epsilon), min_samples=int(minPts), metric='cosine').fit(normalized_data)
    clustering_labels = clustering.labels_
    end = time.perf_counter()
    seconds = (end - start)
    np.save(pathToOut+r"\DBSCAN", clustering_labels)
    np.save(pathToOut+r"\DBSCANTime", seconds)
    f = open(previously_stored_DBSCAN_path, "w")
    f.write(str(normalized_data.shape))
    f.close()
    print("saved new DBSCAN")
else:
    clustering_labels = np.load(pathToOut+r"\DBSCAN.npy")
    seconds = np.load(pathToOut+r"\DBSCANTime.npy")
    print("used loaded DBSCAN")



# Perform nmi
nmi = normalized_mutual_info_score(sDBSCAN, clustering_labels)

# Print results
cl = {}
print("DBSCAN clusters:")
for elem in clustering_labels:
    if elem not in cl:
        cl[int(elem)] = 1
    else:
        cl[int(elem)] = cl[int(elem)] + 1
print(cl)
cl = {}
print("sDBSCAN clusters")
for elem in sDBSCAN:
    if elem not in cl:
        cl[int(elem)] = 1
    else:
        cl[int(elem)] = cl[int(elem)] + 1

print(cl)
print(f"nmi : {(100 * nmi):.2f}%")

sDBSCANStats = np.genfromtxt(sDBSCAN_stats_path, delimiter=",",dtype=str)

print(f"sDBSCAN time: {sDBSCANStats[6]}")

output = (','.join(map(str, np.append(sDBSCANStats, [seconds, nmi]))))
print(output)

#write output in format D,l,m,epsilon,minPts,datasize,sDBSCANtime,DBSCANtime,nmi
with open(pathToOut+r"\dbscan_test_nmi_comparison.csv", "a") as f:
    f.write(output+'\n')