from scipy.cluster.hierarchy import cophenet
from scipy.stats import gmean 
from scipy.stats import pearsonr
import numpy
import hdbscan
import time

# Before you do anything, make sure you have run the NormaliseData project, and run the sHDBSCAN project.

# Input your local path to the folder you want to read input from and write output to.
pathToOut = r"C:\Users\jonas\OneDrive\Dokumenter\ITU\Bachelor_Project_Skæve_Skarve\Code\sDBSCAN\data\out" 

# Input the csv filename for the normalised data you want to run the HDBSCAN on.
normalized_data = numpy.genfromtxt(pathToOut+r"\normalisedDataFashion.csv", delimiter=";", skip_header=1)

# Input the csv filename for the output generated by the sHDBSCAN
approx_dendrogram = numpy.genfromtxt(pathToOut+r"\dendrogram.csv", delimiter=";", skip_header=1)
sHDBSCANStats = numpy.genfromtxt(pathToOut+r"\sHDBSCANStats.csv", delimiter=",",dtype=str)

if(True): #Whether to compute the dendrogram or use a saved one.
    # Perform HDBSCAN
    start = time.perf_counter()
    clusterer = hdbscan.HDBSCAN(min_cluster_size = 4, gen_min_span_tree=True) 
    clusterer.fit(normalized_data)
    true_dendrogram = clusterer.single_linkage_tree_.to_numpy()
    end = time.perf_counter()
    seconds = (end - start)
    numpy.save(pathToOut+r"\trueDendrogram", true_dendrogram)
    numpy.save(pathToOut+r"\trueDendrogramTime", seconds)
else:
    true_dendrogram = numpy.load(pathToOut+r"\trueDendrogram.npy")
    seconds = numpy.load(pathToOut+r"\trueDendrogramTime.npy")

# Prints to make sure the output from both clusterings have the same size
print("normalized_data:", normalized_data.shape)
print("approx_dendrogram:", len(approx_dendrogram))
print("true_dendrogram:", true_dendrogram.shape)
# Perform PCC
cd_approx = cophenet(approx_dendrogram)
cd_true = cophenet(true_dendrogram)
ccc = pearsonr(cd_true, cd_approx)[0]

# MR
mr = gmean(cd_true / cd_approx)
print("MR: ", mr )

# Print results
print("CCC: ", ccc)
print(f"HDBSCAN time: {seconds}")

sHDBSCANStats = numpy.genfromtxt(pathToOut+r"\sHDBSCANStats.csv", delimiter=",",dtype=str)

print(f"sHDBSCAN time: {sHDBSCANStats[5]}")

output = (','.join(map(str, numpy.append(sHDBSCANStats, [seconds, ccc]))))
print(output)

#write output in format D,l,m,k,datasize,sHDBSCANtime,HDBSCANtime,ccc
with open(pathToOut+r"\experiments.csv", "a") as f:
    f.write(output+'\n')
