import sys

from scipy.cluster.hierarchy import cophenet
from scipy.stats import gmean 
import numpy
import hdbscan
import time
import os

if sys.argv[1:] == ["nopcc"]:
    runPcc = False
else:
    runPcc = True

# Before you do anything, make sure you have run the NormaliseData project, and run the sHDBSCAN project.

# Input your local path to the folder you want to read input from and write output to.
pathToOut = r"C:\Users\kassa\Desktop\bachelor\Bachelor_Project_Skaeve_Skarve\Code\BA_Scalable_Clustering\data\out" #Set this to your personal path

# Input the csv filename for the normalised data you want to run the HDBSCAN on.
normalized_data = numpy.genfromtxt(pathToOut+r"\normalisedData.csv", delimiter=";", skip_header=1)

# Input the csv filename for the output generated by the sHDBSCAN
approx_dendrogram = numpy.genfromtxt(pathToOut+r"\dendrogram.csv", delimiter=";", skip_header=1)
sHDBSCANStats = numpy.genfromtxt(pathToOut+r"\sHDBSCANStats.csv", delimiter=",",dtype=str)

lastSavedPath = pathToOut+r"\lastSaved.txt"
if not os.path.exists(lastSavedPath):
    with open(lastSavedPath, "w") as file:
        file.write("Nothing")

f = open(lastSavedPath)
lastSaved = f.read()
f.close()

if(str(lastSaved) != str(normalized_data.shape)): #Whether to compute the dendrogram or use a saved one.
    # Perform HDBSCAN
    start = time.perf_counter()
    clusterer = hdbscan.HDBSCAN(min_samples= 5, gen_min_span_tree=True) 
    clusterer.fit(normalized_data)
    true_dendrogram = clusterer.single_linkage_tree_.to_numpy()
    end = time.perf_counter()
    seconds = (end - start)
    numpy.save(pathToOut+r"\trueDendrogram", true_dendrogram)
    numpy.save(pathToOut+r"\trueDendrogramTime", seconds)
    f = open(lastSavedPath, "w")
    f.write(str(normalized_data.shape))
    f.close()
    print("saved new true dendrogram")
else:
    true_dendrogram = numpy.load(pathToOut+r"\trueDendrogram.npy")
    seconds = numpy.load(pathToOut+r"\trueDendrogramTime.npy")
    print("used loaded true dendrogram")


# Prints to make sure the output from both clusterings have the same size
print("normalized_data:", normalized_data.shape)
print("approx_dendrogram:", len(approx_dendrogram))
print("true_dendrogram:", true_dendrogram.shape)


# Perform PCC
cd_approx = cophenet(approx_dendrogram)
cd_true = cophenet(true_dendrogram)


def euclidean_to_cosine(d):
    d = numpy.asarray(d)
    return (d ** 2) / 2

cos_cd_true = euclidean_to_cosine(cd_true)

# FIXED: Correct streaming Pearson correlation computation
def chunked_pearsonr(x_full, y_full, chunk_size=50_000):
    """
    Compute Pearson correlation coefficient in chunks to avoid memory overflow.
    Uses Welford-style online algorithm for numerical stability.
    """
    n = len(x_full)
    
    # First pass: compute means
    sum_x = 0.0
    sum_y = 0.0
    n_chunks = (n + chunk_size - 1) // chunk_size
    
    for i in range(n_chunks):
        start = i * chunk_size
        end = min(start + chunk_size, n)
        x = x_full[start:end]
        y = y_full[start:end]
        sum_x += x.sum()
        sum_y += y.sum()
    
    mean_x = sum_x / n
    mean_y = sum_y / n
    
    # Second pass: compute covariance and variances using centered deviations
    cov_xy = 0.0
    var_x = 0.0
    var_y = 0.0
    
    for i in range(n_chunks):
        start = i * chunk_size
        end = min(start + chunk_size, n)
        x = x_full[start:end]
        y = y_full[start:end]
        
        dx = x - mean_x
        dy = y - mean_y
        
        cov_xy += (dx * dy).sum()
        var_x += (dx ** 2).sum()
        var_y += (dy ** 2).sum()
    
    # Compute Pearson correlation
    pcc = cov_xy / (var_x**0.5 * var_y**0.5)
    return pcc

pcc = chunked_pearsonr(cd_approx, cos_cd_true, chunk_size=50_000)

# MR
mr = gmean(cos_cd_true / cd_approx)
print("MR: ", mr )

# Print results
print("CCC: ", pcc)
print(f"HDBSCAN time: {seconds}")

sHDBSCANStats = numpy.genfromtxt(pathToOut+r"\sHDBSCANStats.csv", delimiter=",",dtype=str)

print(f"sHDBSCAN time: {sHDBSCANStats[5]}")

output = (','.join(map(str, numpy.append(sHDBSCANStats, [seconds, pcc, mr]))))
print(output)

#write output in format D,l,m,k,datasize,sHDBSCANtime,HDBSCANtime,ccc
with open(pathToOut+r"\test_newpcc.csv", "a") as f:
    f.write(output+'\n')
