from scipy.cluster.hierarchy import cophenet
from scipy.stats import gmean 
from scipy.stats import pearsonr
import numpy
import hdbscan
import time
import os

# Before you do anything, make sure you have run the NormaliseData project, and run the sHDBSCAN project.

# Input your local path to the folder you want to read input from and write output to.
pathToOut = r"C:\Users\kassa\Desktop\bachelor\Bachelor_Project_Skaeve_Skarve\Code\BA_Scalable_Clustering\data\out" #Set this to your personal path

# Input the csv filename for the normalised data you want to run the HDBSCAN on.
normalized_data = numpy.genfromtxt(pathToOut+r"\normalisedDataMnistTrain500.csv", delimiter=";", skip_header=1)

# Input the csv filename for the output generated by the sHDBSCAN
approx_dendrogram = numpy.genfromtxt(pathToOut+r"\dendrogram.csv", delimiter=";", skip_header=1)
sHDBSCANStats = numpy.genfromtxt(pathToOut+r"\sHDBSCANStats.csv", delimiter=",",dtype=str)

lastSavedPath = pathToOut+r"\lastSaved.txt"
if not os.path.exists(lastSavedPath):
    with open(lastSavedPath, "w") as file:
        file.write("Nothing")

f = open(lastSavedPath)
lastSaved = f.read()
f.close()

if(str(lastSaved) != str(normalized_data.shape)): #Whether to compute the dendrogram or use a saved one.
    # Perform HDBSCAN
    start = time.perf_counter()
    clusterer = hdbscan.HDBSCAN(min_samples= 5, gen_min_span_tree=True) 
    clusterer.fit(normalized_data)
    true_dendrogram = clusterer.single_linkage_tree_.to_numpy()
    end = time.perf_counter()
    seconds = (end - start)
    numpy.save(pathToOut+r"\trueDendrogram", true_dendrogram)
    numpy.save(pathToOut+r"\trueDendrogramTime", seconds)
    f = open(lastSavedPath, "w")
    f.write(str(normalized_data.shape))
    f.close()
    print("saved new true dendrogram")
else:
    true_dendrogram = numpy.load(pathToOut+r"\trueDendrogram.npy")
    seconds = numpy.load(pathToOut+r"\trueDendrogramTime.npy")
    print("used loaded true dendrogram")


# Prints to make sure the output from both clusterings have the same size
print("normalized_data:", normalized_data.shape)
print("approx_dendrogram:", len(approx_dendrogram))
print("true_dendrogram:", true_dendrogram.shape)


# Perform PCC
cd_approx = cophenet(approx_dendrogram)
cd_true = cophenet(true_dendrogram)


def euclidean_to_cosine(d):
    d = numpy.asarray(d)
    return (d ** 2) / 2

cos_cd_true = euclidean_to_cosine(cd_true)
pcc = pearsonr(cos_cd_true, cos_cd_true)[0]

# MR
mr = gmean(cos_cd_true / cd_approx)
print("MR: ", mr )

# Print results
print("CCC: ", pcc)
print(f"HDBSCAN time: {seconds}")

sHDBSCANStats = numpy.genfromtxt(pathToOut+r"\sHDBSCANStats.csv", delimiter=",",dtype=str)

print(f"sHDBSCAN time: {sHDBSCANStats[5]}")

output = (','.join(map(str, numpy.append(sHDBSCANStats, [seconds, pcc]))))
print(output)

#write output in format D,l,m,k,datasize,sHDBSCANtime,HDBSCANtime,ccc
with open(pathToOut+r"\runtime_1.csv", "a") as f:
    f.write(output+'\n')
